create table if not exists products
(
    id                        bigint generated by default as identity
        primary key,
    creation_date             timestamp,
    modification_date         timestamp,
    product_name              varchar(255),
    product_price             double precision,
    product_quantity_in_stock bigint
);

alter table products
    owner to postgres;

create table if not exists roles
(
    id                bigint generated by default as identity (maxvalue 2147483647)
        primary key,
    creation_date     timestamp,
    modification_date timestamp,
    role_name         varchar(255)
);

alter table roles
    owner to postgres;

create table if not exists users
(
    id                bigint generated by default as identity (maxvalue 2147483647)
        primary key,
    birth             timestamp,
    creation_date     timestamp,
    user_login        varchar(255),
    user_password     varchar(255),
    email             varchar(255),
    first_name        varchar(255),
    is_deleted        boolean default false not null,
    last_name         varchar(255),
    modification_date timestamp
);

alter table users
    owner to postgres;

create table if not exists purchases
(
    id                bigint generated by default as identity (maxvalue 2147483647)
        primary key,
    creation_date     timestamp,
    modification_date timestamp,
    product_price     double precision,
    user_id           bigint not null
        constraint purchases_users_id_fk
            references users
            on update cascade on delete cascade,
    product_id        integer
        constraint purchases_products_id_fk
            references products
            on update cascade on delete cascade
);

alter table purchases
    owner to postgres;

create table if not exists l_role_user
(
    id      bigserial
        constraint l_role_user_pk
            primary key,
    user_id bigint not null
        constraint l_role_user_users_id_fk
            references users
            on update cascade on delete cascade,
    role_id bigint not null
        constraint l_role_user_roles_id_fk
            references roles
            on update cascade on delete cascade
);

alter table l_role_user
    owner to postgres;

create unique index if not exists l_role_user_id_uindex
    on l_role_user (id);

create index if not exists l_role_user_user_id_role_id_index
    on l_role_user (user_id, role_id);
